export class ShippingCountry {
    id: number;
    title: string;
    euCountry?: boolean;
    singleAmount?: number;
    extraAmount?: number;
}

export const ShippingCountries: ShippingCountry[] = [
    { id: 1, title: 'European Union' },
    { id: 2, title: 'Afghanistan' },
    { id: 3, title: 'Aland Islands' },
    { id: 4, title: 'Albania' },
    { id: 5, title: 'Algeria' },
    { id: 6, title: 'American Samoa' },
    { id: 7, title: 'Andorra' },
    { id: 8, title: 'Angola' },
    { id: 9, title: 'Anguilla' },
    { id: 10, title: 'Antarctica' },
    { id: 11, title: 'Antigua and Barbuda' },
    { id: 12, title: 'Argentina' },
    { id: 13, title: 'Armenia' },
    { id: 14, title: 'Aruba' },
    { id: 15, title: 'Australia' },
    { id: 16, title: 'Austria', euCountry: true },
    { id: 17, title: 'Azerbaijan' },
    { id: 18, title: 'Bahrain' },
    { id: 19, title: 'Bangladesh' },
    { id: 20, title: 'Barbados' },
    { id: 21, title: 'Belarus' },
    { id: 22, title: 'Belgium', euCountry: true },
    { id: 23, title: 'Belize' },
    { id: 24, title: 'Benin' },
    { id: 25, title: 'Bermuda' },
    { id: 26, title: 'Bhutan' },
    { id: 27, title: 'Bolivia' },
    { id: 28, title: 'Bosnia and Herzegovina' },
    { id: 29, title: 'Botswana' },
    { id: 30, title: 'Bouvet Island' },
    { id: 31, title: 'Brazil' },
    { id: 32, title: 'British Indian Ocean Territory' },
    { id: 33, title: 'British Virgin Islands' },
    { id: 34, title: 'Brunei' },
    { id: 35, title: 'Bulgaria', euCountry: true },
    { id: 36, title: 'Burkina Faso' },
    { id: 37, title: 'Burundi' },
    { id: 38, title: 'Cambodia' },
    { id: 39, title: 'Cameroon' },
    { id: 40, title: 'Canada' },
    { id: 41, title: 'Cape Verde' },
    { id: 42, title: 'Caribbean Netherlands' },
    { id: 43, title: 'Cayman Islands' },
    { id: 44, title: 'Central African Republic' },
    { id: 45, title: 'Chad' },
    { id: 46, title: 'Chile' },
    { id: 47, title: 'China' },
    { id: 48, title: 'Christmas Island' },
    { id: 49, title: 'Cocos (Keeling) Islands' },
    { id: 50, title: 'Colombia' },
    { id: 51, title: 'Comoros' },
    { id: 52, title: 'Congo' },
    { id: 53, title: 'Cook Islands' },
    { id: 54, title: 'Costa Rica' },
    { id: 55, title: 'Croatia', euCountry: true },
    { id: 56, title: 'Curaçao' },
    { id: 57, title: 'Cyprus', euCountry: true },
    { id: 58, title: 'Czech Republic', euCountry: true },
    { id: 59, title: 'Democratic Republic of Congo' },
    { id: 60, title: 'Denmark', euCountry: true },
    { id: 61, title: 'Disputed Territory' },
    { id: 62, title: 'Djibouti' },
    { id: 63, title: 'Dominica' },
    { id: 64, title: 'Dominican Republic' },
    { id: 65, title: 'East Timor' },
    { id: 66, title: 'Ecuador' },
    { id: 67, title: 'Egypt' },
    { id: 68, title: 'El Salvador' },
    { id: 69, title: 'Equatorial Guinea' },
    { id: 70, title: 'Eritrea' },
    { id: 71, title: 'Estonia', euCountry: true },
    { id: 72, title: 'Ethiopia' },
    { id: 73, title: 'Falkland Islands' },
    { id: 74, title: 'Faroe Islands' },
    { id: 75, title: 'Federated States of Micronesia' },
    { id: 76, title: 'Fiji' },
    { id: 77, title: 'Finland', euCountry: true },
    { id: 78, title: 'France', euCountry: true },
    { id: 79, title: 'French Guiana' },
    { id: 80, title: 'French Polynesia' },
    { id: 81, title: 'French Southern Territories' },
    { id: 82, title: 'Gabon' },
    { id: 83, title: 'Gambia' },
    { id: 84, title: 'Georgia' },
    { id: 85, title: 'Germany', euCountry: true },
    { id: 86, title: 'Ghana' },
    { id: 87, title: 'Gibraltar' },
    { id: 88, title: 'Greece', euCountry: true },
    { id: 89, title: 'Greenland' },
    { id: 90, title: 'Grenada' },
    { id: 91, title: 'Guadeloupe' },
    { id: 92, title: 'Guam' },
    { id: 93, title: 'Guatemala' },
    { id: 94, title: 'Guinea' },
    { id: 95, title: 'Guinea-Bissau' },
    { id: 96, title: 'Guyana' },
    { id: 97, title: 'Haiti' },
    { id: 98, title: 'Heard Island and McDonald Islands' },
    { id: 99, title: 'Holy See (Vatican City State)' },
    { id: 100, title: 'Honduras' },
    { id: 101, title: 'Hong Kong' },
    { id: 102, title: 'Hungary', euCountry: true },
    { id: 103, title: 'Iceland' },
    { id: 104, title: 'India' },
    { id: 105, title: 'Indonesia' },
    { id: 106, title: 'Iraq' },
    { id: 107, title: 'Iraq-Saudi Arabia Neutral Zone' },
    { id: 108, title: 'Ireland', euCountry: true },
    { id: 109, title: 'Israel' },
    { id: 110, title: 'Italy', euCountry: true },
    { id: 111, title: 'Ivory Coast' },
    { id: 112, title: 'Jamaica' },
    { id: 113, title: 'Japan' },
    { id: 114, title: 'Jordan' },
    { id: 115, title: 'Kazakhstan' },
    { id: 116, title: 'Kenya' },
    { id: 117, title: 'Kiribati' },
    { id: 118, title: 'Kosovo' },
    { id: 119, title: 'Kuwait' },
    { id: 120, title: 'Kyrgyzstan' },
    { id: 121, title: 'Laos' },
    { id: 122, title: 'Latvia', euCountry: true },
    { id: 123, title: 'Lebanon' },
    { id: 124, title: 'Lesotho' },
    { id: 125, title: 'Liberia' },
    { id: 126, title: 'Libya' },
    { id: 127, title: 'Liechtenstein' },
    { id: 128, title: 'Lithuania', euCountry: true },
    { id: 129, title: 'Luxembourg', euCountry: true },
    { id: 130, title: 'Macao' },
    { id: 131, title: 'Macedonia' },
    { id: 132, title: 'Madagascar' },
    { id: 133, title: 'Malawi' },
    { id: 134, title: 'Malaysia' },
    { id: 135, title: 'Maldives' },
    { id: 136, title: 'Mali' },
    { id: 137, title: 'Malta', euCountry: true },
    { id: 138, title: 'Marshall Islands' },
    { id: 139, title: 'Martinique' },
    { id: 140, title: 'Mauritania' },
    { id: 141, title: 'Mauritius' },
    { id: 142, title: 'Mayotte' },
    { id: 143, title: 'Mexico' },
    { id: 144, title: 'Moldova' },
    { id: 145, title: 'Monaco' },
    { id: 146, title: 'Mongolia' },
    { id: 147, title: 'Montenegro' },
    { id: 148, title: 'Montserrat' },
    { id: 149, title: 'Morocco' },
    { id: 150, title: 'Mozambique' },
    { id: 151, title: 'Myanmar' },
    { id: 152, title: 'Namibia' },
    { id: 153, title: 'Nauru' },
    { id: 154, title: 'Nepal' },
    { id: 155, title: 'Netherlands', euCountry: true },
    { id: 156, title: 'New Caledonia' },
    { id: 157, title: 'New Zealand' },
    { id: 158, title: 'Nicaragua' },
    { id: 159, title: 'Niger' },
    { id: 160, title: 'Nigeria' },
    { id: 161, title: 'Niue' },
    { id: 162, title: 'Norfolk Island' },
    { id: 163, title: 'Northern Mariana Islands' },
    { id: 164, title: 'Norway' },
    { id: 165, title: 'Oman' },
    { id: 166, title: 'Pakistan' },
    { id: 167, title: 'Palau' },
    { id: 168, title: 'Palestine' },
    { id: 169, title: 'Panama' },
    { id: 170, title: 'Papua New Guinea' },
    { id: 171, title: 'Paraguay' },
    { id: 172, title: 'Peru' },
    { id: 173, title: 'Philippines' },
    { id: 174, title: 'Pitcairn Islands' },
    { id: 175, title: 'Poland', euCountry: true },
    { id: 176, title: 'Portugal', euCountry: true },
    { id: 177, title: 'Puerto Rico' },
    { id: 178, title: 'Qatar' },
    { id: 179, title: 'Romania', euCountry: true },
    { id: 180, title: 'Russia' },
    { id: 181, title: 'Rwanda' },
    { id: 182, title: 'Réunion' },
    { id: 183, title: 'Saint Barthélemy' },
    { id: 184, title: 'Saint Helena, Ascension and Tristan da Cunha' },
    { id: 185, title: 'Saint Kitts and Nevis' },
    { id: 186, title: 'Saint Lucia' },
    { id: 187, title: 'Saint Martin (French part)' },
    { id: 188, title: 'Saint Pierre and Miquelon' },
    { id: 189, title: 'Saint Vincent and the Grenadines' },
    { id: 190, title: 'Samoa' },
    { id: 191, title: 'San Marino' },
    { id: 192, title: 'Sao Tome and Principe' },
    { id: 193, title: 'Saudi Arabia' },
    { id: 194, title: 'Senegal' },
    { id: 195, title: 'Serbia' },
    { id: 196, title: 'Seychelles' },
    { id: 197, title: 'Sierra Leone' },
    { id: 198, title: 'Singapore' },
    { id: 199, title: 'Sint Maarten (Dutch part)' },
    { id: 200, title: 'Slovakia', euCountry: true },
    { id: 201, title: 'Slovenia', euCountry: true },
    { id: 202, title: 'Solomon Islands' },
    { id: 203, title: 'Somalia' },
    { id: 204, title: 'South Africa' },
    { id: 205, title: 'South Georgia and the South Sandwich Islands' },
    { id: 206, title: 'South Korea' },
    { id: 207, title: 'Spain', euCountry: true },
    { id: 208, title: 'Spratly Islands' },
    { id: 209, title: 'Sri Lanka' },
    { id: 210, title: 'Sudan' },
    { id: 211, title: 'Suriname' },
    { id: 212, title: 'Svalbard and Jan Mayen' },
    { id: 213, title: 'Swaziland' },
    { id: 214, title: 'Sweden', euCountry: true },
    { id: 215, title: 'Switzerland' },
    { id: 216, title: 'Taiwan' },
    { id: 217, title: 'Tajikistan' },
    { id: 218, title: 'Tanzania, United Republic of' },
    { id: 219, title: 'Thailand' },
    { id: 220, title: 'The Bahamas' },
    { id: 221, title: 'Togo' },
    { id: 222, title: 'Tokelau' },
    { id: 223, title: 'Tonga' },
    { id: 224, title: 'Trinidad and Tobago' },
    { id: 225, title: 'Tunisia' },
    { id: 226, title: 'Turkey' },
    { id: 227, title: 'Turkmenistan' },
    { id: 228, title: 'Turks and Caicos Islands' },
    { id: 229, title: 'Tuvalu' },
    { id: 230, title: 'Uganda' },
    { id: 231, title: 'Ukraine' },
    { id: 232, title: 'United Arab Emirates' },
    { id: 233, title: 'United Kingdom', euCountry: true },
    { id: 234, title: 'United Nations Neutral Zone' },
    { id: 235, title: 'United States' },
    { id: 236, title: 'United States Minor Outlying Islands' },
    { id: 237, title: 'Uruguay' },
    { id: 238, title: 'Uzbekistan' },
    { id: 239, title: 'Vanuatu' },
    { id: 240, title: 'Venezuela' },
    { id: 241, title: 'Vietnam' },
    { id: 242, title: 'Virgin Islands, U.S.' },
    { id: 243, title: 'Wallis and Futuna' },
    { id: 244, title: 'Western Sahara' },
    { id: 245, title: 'Yemen' },
    { id: 246, title: 'Zambia' },
    { id: 247, title: 'Zimbabwe' }
];
