export class ShippingCountry {
    id: number;
    title: string;
    singleAmount: number;
    extraAmount: number;
}

export const ShippingCountries: ShippingCountry[] = [
    { id: 1, title: 'European Union', singleAmount: 0, extraAmount: 0 },
    { id: 2, title: 'Afghanistan', singleAmount: 0, extraAmount: 0 },
    { id: 3, title: 'Aland Islands', singleAmount: 0, extraAmount: 0 },
    { id: 4, title: 'Albania', singleAmount: 0, extraAmount: 0 },
    { id: 5, title: 'Algeria', singleAmount: 0, extraAmount: 0 },
    { id: 6, title: 'American Samoa', singleAmount: 0, extraAmount: 0 },
    { id: 7, title: 'Andorra', singleAmount: 0, extraAmount: 0 },
    { id: 8, title: 'Angola', singleAmount: 0, extraAmount: 0 },
    { id: 9, title: 'Anguilla', singleAmount: 0, extraAmount: 0 },
    { id: 10, title: 'Antarctica', singleAmount: 0, extraAmount: 0 },
    { id: 11, title: 'Antigua and Barbuda', singleAmount: 0, extraAmount: 0 },
    { id: 12, title: 'Argentina', singleAmount: 0, extraAmount: 0 },
    { id: 13, title: 'Armenia', singleAmount: 0, extraAmount: 0 },
    { id: 14, title: 'Aruba', singleAmount: 0, extraAmount: 0 },
    { id: 15, title: 'Australia', singleAmount: 0, extraAmount: 0 },
    { id: 16, title: 'Austria', singleAmount: 0, extraAmount: 0 },
    { id: 17, title: 'Azerbaijan', singleAmount: 0, extraAmount: 0 },
    { id: 18, title: 'Bahrain', singleAmount: 0, extraAmount: 0 },
    { id: 19, title: 'Bangladesh', singleAmount: 0, extraAmount: 0 },
    { id: 20, title: 'Barbados', singleAmount: 0, extraAmount: 0 },
    { id: 21, title: 'Belarus', singleAmount: 0, extraAmount: 0 },
    { id: 22, title: 'Belgium', singleAmount: 0, extraAmount: 0 },
    { id: 23, title: 'Belize', singleAmount: 0, extraAmount: 0 },
    { id: 24, title: 'Benin', singleAmount: 0, extraAmount: 0 },
    { id: 25, title: 'Bermuda', singleAmount: 0, extraAmount: 0 },
    { id: 26, title: 'Bhutan', singleAmount: 0, extraAmount: 0 },
    { id: 27, title: 'Bolivia', singleAmount: 0, extraAmount: 0 },
    { id: 28, title: 'Bosnia and Herzegovina', singleAmount: 0, extraAmount: 0 },
    { id: 29, title: 'Botswana', singleAmount: 0, extraAmount: 0 },
    { id: 30, title: 'Bouvet Island', singleAmount: 0, extraAmount: 0 },
    { id: 31, title: 'Brazil', singleAmount: 0, extraAmount: 0 },
    { id: 32, title: 'British Indian Ocean Territory', singleAmount: 0, extraAmount: 0 },
    { id: 33, title: 'British Virgin Islands', singleAmount: 0, extraAmount: 0 },
    { id: 34, title: 'Brunei', singleAmount: 0, extraAmount: 0 },
    { id: 35, title: 'Bulgaria', singleAmount: 0, extraAmount: 0 },
    { id: 36, title: 'Burkina Faso', singleAmount: 0, extraAmount: 0 },
    { id: 37, title: 'Burundi', singleAmount: 0, extraAmount: 0 },
    { id: 38, title: 'Cambodia', singleAmount: 0, extraAmount: 0 },
    { id: 39, title: 'Cameroon', singleAmount: 0, extraAmount: 0 },
    { id: 40, title: 'Canada', singleAmount: 0, extraAmount: 0 },
    { id: 41, title: 'Cape Verde', singleAmount: 0, extraAmount: 0 },
    { id: 42, title: 'Caribbean Netherlands', singleAmount: 0, extraAmount: 0 },
    { id: 43, title: 'Cayman Islands', singleAmount: 0, extraAmount: 0 },
    { id: 44, title: 'Central African Republic', singleAmount: 0, extraAmount: 0 },
    { id: 45, title: 'Chad', singleAmount: 0, extraAmount: 0 },
    { id: 46, title: 'Chile', singleAmount: 0, extraAmount: 0 },
    { id: 47, title: 'China', singleAmount: 0, extraAmount: 0 },
    { id: 48, title: 'Christmas Island', singleAmount: 0, extraAmount: 0 },
    { id: 49, title: 'Cocos (Keeling) Islands', singleAmount: 0, extraAmount: 0 },
    { id: 50, title: 'Colombia', singleAmount: 0, extraAmount: 0 },
    { id: 51, title: 'Comoros', singleAmount: 0, extraAmount: 0 },
    { id: 52, title: 'Congo', singleAmount: 0, extraAmount: 0 },
    { id: 53, title: 'Cook Islands', singleAmount: 0, extraAmount: 0 },
    { id: 54, title: 'Costa Rica', singleAmount: 0, extraAmount: 0 },
    { id: 55, title: 'Croatia', singleAmount: 0, extraAmount: 0 },
    { id: 56, title: 'Curaçao', singleAmount: 0, extraAmount: 0 },
    { id: 57, title: 'Cyprus', singleAmount: 0, extraAmount: 0 },
    { id: 58, title: 'Czech Republic', singleAmount: 0, extraAmount: 0 },
    { id: 59, title: 'Democratic Republic of Congo', singleAmount: 0, extraAmount: 0 },
    { id: 60, title: 'Denmark', singleAmount: 0, extraAmount: 0 },
    { id: 61, title: 'Disputed Territory', singleAmount: 0, extraAmount: 0 },
    { id: 62, title: 'Djibouti', singleAmount: 0, extraAmount: 0 },
    { id: 63, title: 'Dominica', singleAmount: 0, extraAmount: 0 },
    { id: 64, title: 'Dominican Republic', singleAmount: 0, extraAmount: 0 },
    { id: 65, title: 'East Timor', singleAmount: 0, extraAmount: 0 },
    { id: 66, title: 'Ecuador', singleAmount: 0, extraAmount: 0 },
    { id: 67, title: 'Egypt', singleAmount: 0, extraAmount: 0 },
    { id: 68, title: 'El Salvador', singleAmount: 0, extraAmount: 0 },
    { id: 69, title: 'Equatorial Guinea', singleAmount: 0, extraAmount: 0 },
    { id: 70, title: 'Eritrea', singleAmount: 0, extraAmount: 0 },
    { id: 71, title: 'Estonia', singleAmount: 0, extraAmount: 0 },
    { id: 72, title: 'Ethiopia', singleAmount: 0, extraAmount: 0 },
    { id: 73, title: 'Falkland Islands', singleAmount: 0, extraAmount: 0 },
    { id: 74, title: 'Faroe Islands', singleAmount: 0, extraAmount: 0 },
    { id: 75, title: 'Federated States of Micronesia', singleAmount: 0, extraAmount: 0 },
    { id: 76, title: 'Fiji', singleAmount: 0, extraAmount: 0 },
    { id: 77, title: 'Finland', singleAmount: 0, extraAmount: 0 },
    { id: 78, title: 'France', singleAmount: 0, extraAmount: 0 },
    { id: 79, title: 'French Guiana', singleAmount: 0, extraAmount: 0 },
    { id: 80, title: 'French Polynesia', singleAmount: 0, extraAmount: 0 },
    { id: 81, title: 'French Southern Territories', singleAmount: 0, extraAmount: 0 },
    { id: 82, title: 'Gabon', singleAmount: 0, extraAmount: 0 },
    { id: 83, title: 'Gambia', singleAmount: 0, extraAmount: 0 },
    { id: 84, title: 'Georgia', singleAmount: 0, extraAmount: 0 },
    { id: 85, title: 'Germany', singleAmount: 0, extraAmount: 0 },
    { id: 86, title: 'Ghana', singleAmount: 0, extraAmount: 0 },
    { id: 87, title: 'Gibraltar', singleAmount: 0, extraAmount: 0 },
    { id: 88, title: 'Greece', singleAmount: 0, extraAmount: 0 },
    { id: 89, title: 'Greenland', singleAmount: 0, extraAmount: 0 },
    { id: 90, title: 'Grenada', singleAmount: 0, extraAmount: 0 },
    { id: 91, title: 'Guadeloupe', singleAmount: 0, extraAmount: 0 },
    { id: 92, title: 'Guam', singleAmount: 0, extraAmount: 0 },
    { id: 93, title: 'Guatemala', singleAmount: 0, extraAmount: 0 },
    { id: 94, title: 'Guinea', singleAmount: 0, extraAmount: 0 },
    { id: 95, title: 'Guinea-Bissau', singleAmount: 0, extraAmount: 0 },
    { id: 96, title: 'Guyana', singleAmount: 0, extraAmount: 0 },
    { id: 97, title: 'Haiti', singleAmount: 0, extraAmount: 0 },
    { id: 98, title: 'Heard Island and McDonald Islands', singleAmount: 0, extraAmount: 0 },
    { id: 99, title: 'Holy See (Vatican City State)', singleAmount: 0, extraAmount: 0 },
    { id: 100, title: 'Honduras', singleAmount: 0, extraAmount: 0 },
    { id: 101, title: 'Hong Kong', singleAmount: 0, extraAmount: 0 },
    { id: 102, title: 'Hungary', singleAmount: 0, extraAmount: 0 },
    { id: 103, title: 'Iceland', singleAmount: 0, extraAmount: 0 },
    { id: 104, title: 'India', singleAmount: 0, extraAmount: 0 },
    { id: 105, title: 'Indonesia', singleAmount: 0, extraAmount: 0 },
    { id: 106, title: 'Iraq', singleAmount: 0, extraAmount: 0 },
    { id: 107, title: 'Iraq-Saudi Arabia Neutral Zone', singleAmount: 0, extraAmount: 0 },
    { id: 108, title: 'Ireland', singleAmount: 0, extraAmount: 0 },
    { id: 109, title: 'Israel', singleAmount: 0, extraAmount: 0 },
    { id: 110, title: 'Italy', singleAmount: 0, extraAmount: 0 },
    { id: 111, title: 'Ivory Coast', singleAmount: 0, extraAmount: 0 },
    { id: 112, title: 'Jamaica', singleAmount: 0, extraAmount: 0 },
    { id: 113, title: 'Japan', singleAmount: 0, extraAmount: 0 },
    { id: 114, title: 'Jordan', singleAmount: 0, extraAmount: 0 },
    { id: 115, title: 'Kazakhstan', singleAmount: 0, extraAmount: 0 },
    { id: 116, title: 'Kenya', singleAmount: 0, extraAmount: 0 },
    { id: 117, title: 'Kiribati', singleAmount: 0, extraAmount: 0 },
    { id: 118, title: 'Kosovo', singleAmount: 0, extraAmount: 0 },
    { id: 119, title: 'Kuwait', singleAmount: 0, extraAmount: 0 },
    { id: 120, title: 'Kyrgyzstan', singleAmount: 0, extraAmount: 0 },
    { id: 121, title: 'Laos', singleAmount: 0, extraAmount: 0 },
    { id: 122, title: 'Latvia', singleAmount: 0, extraAmount: 0 },
    { id: 123, title: 'Lebanon', singleAmount: 0, extraAmount: 0 },
    { id: 124, title: 'Lesotho', singleAmount: 0, extraAmount: 0 },
    { id: 125, title: 'Liberia', singleAmount: 0, extraAmount: 0 },
    { id: 126, title: 'Libya', singleAmount: 0, extraAmount: 0 },
    { id: 127, title: 'Liechtenstein', singleAmount: 0, extraAmount: 0 },
    { id: 128, title: 'Lithuania', singleAmount: 0, extraAmount: 0 },
    { id: 129, title: 'Luxembourg', singleAmount: 0, extraAmount: 0 },
    { id: 130, title: 'Macao', singleAmount: 0, extraAmount: 0 },
    { id: 131, title: 'Macedonia', singleAmount: 0, extraAmount: 0 },
    { id: 132, title: 'Madagascar', singleAmount: 0, extraAmount: 0 },
    { id: 133, title: 'Malawi', singleAmount: 0, extraAmount: 0 },
    { id: 134, title: 'Malaysia', singleAmount: 0, extraAmount: 0 },
    { id: 135, title: 'Maldives', singleAmount: 0, extraAmount: 0 },
    { id: 136, title: 'Mali', singleAmount: 0, extraAmount: 0 },
    { id: 137, title: 'Malta', singleAmount: 0, extraAmount: 0 },
    { id: 138, title: 'Marshall Islands', singleAmount: 0, extraAmount: 0 },
    { id: 139, title: 'Martinique', singleAmount: 0, extraAmount: 0 },
    { id: 140, title: 'Mauritania', singleAmount: 0, extraAmount: 0 },
    { id: 141, title: 'Mauritius', singleAmount: 0, extraAmount: 0 },
    { id: 142, title: 'Mayotte', singleAmount: 0, extraAmount: 0 },
    { id: 143, title: 'Mexico', singleAmount: 0, extraAmount: 0 },
    { id: 144, title: 'Moldova', singleAmount: 0, extraAmount: 0 },
    { id: 145, title: 'Monaco', singleAmount: 0, extraAmount: 0 },
    { id: 146, title: 'Mongolia', singleAmount: 0, extraAmount: 0 },
    { id: 147, title: 'Montenegro', singleAmount: 0, extraAmount: 0 },
    { id: 148, title: 'Montserrat', singleAmount: 0, extraAmount: 0 },
    { id: 149, title: 'Morocco', singleAmount: 0, extraAmount: 0 },
    { id: 150, title: 'Mozambique', singleAmount: 0, extraAmount: 0 },
    { id: 151, title: 'Myanmar', singleAmount: 0, extraAmount: 0 },
    { id: 152, title: 'Namibia', singleAmount: 0, extraAmount: 0 },
    { id: 153, title: 'Nauru', singleAmount: 0, extraAmount: 0 },
    { id: 154, title: 'Nepal', singleAmount: 0, extraAmount: 0 },
    { id: 155, title: 'Netherlands', singleAmount: 0, extraAmount: 0 },
    { id: 156, title: 'New Caledonia', singleAmount: 0, extraAmount: 0 },
    { id: 157, title: 'New Zealand', singleAmount: 0, extraAmount: 0 },
    { id: 158, title: 'Nicaragua', singleAmount: 0, extraAmount: 0 },
    { id: 159, title: 'Niger', singleAmount: 0, extraAmount: 0 },
    { id: 160, title: 'Nigeria', singleAmount: 0, extraAmount: 0 },
    { id: 161, title: 'Niue', singleAmount: 0, extraAmount: 0 },
    { id: 162, title: 'Norfolk Island', singleAmount: 0, extraAmount: 0 },
    { id: 163, title: 'Northern Mariana Islands', singleAmount: 0, extraAmount: 0 },
    { id: 164, title: 'Norway', singleAmount: 0, extraAmount: 0 },
    { id: 165, title: 'Oman', singleAmount: 0, extraAmount: 0 },
    { id: 166, title: 'Pakistan', singleAmount: 0, extraAmount: 0 },
    { id: 167, title: 'Palau', singleAmount: 0, extraAmount: 0 },
    { id: 168, title: 'Palestine', singleAmount: 0, extraAmount: 0 },
    { id: 169, title: 'Panama', singleAmount: 0, extraAmount: 0 },
    { id: 170, title: 'Papua New Guinea', singleAmount: 0, extraAmount: 0 },
    { id: 171, title: 'Paraguay', singleAmount: 0, extraAmount: 0 },
    { id: 172, title: 'Peru', singleAmount: 0, extraAmount: 0 },
    { id: 173, title: 'Philippines', singleAmount: 0, extraAmount: 0 },
    { id: 174, title: 'Pitcairn Islands', singleAmount: 0, extraAmount: 0 },
    { id: 175, title: 'Poland', singleAmount: 0, extraAmount: 0 },
    { id: 176, title: 'Portugal', singleAmount: 0, extraAmount: 0 },
    { id: 177, title: 'Puerto Rico', singleAmount: 0, extraAmount: 0 },
    { id: 178, title: 'Qatar', singleAmount: 0, extraAmount: 0 },
    { id: 179, title: 'Romania', singleAmount: 0, extraAmount: 0 },
    { id: 180, title: 'Russia', singleAmount: 0, extraAmount: 0 },
    { id: 181, title: 'Rwanda', singleAmount: 0, extraAmount: 0 },
    { id: 182, title: 'Réunion', singleAmount: 0, extraAmount: 0 },
    { id: 183, title: 'Saint Barthélemy', singleAmount: 0, extraAmount: 0 },
    { id: 184, title: 'Saint Helena, Ascension and Tristan da Cunha', singleAmount: 0, extraAmount: 0 },
    { id: 185, title: 'Saint Kitts and Nevis', singleAmount: 0, extraAmount: 0 },
    { id: 186, title: 'Saint Lucia', singleAmount: 0, extraAmount: 0 },
    { id: 187, title: 'Saint Martin (French part)', singleAmount: 0, extraAmount: 0 },
    { id: 188, title: 'Saint Pierre and Miquelon', singleAmount: 0, extraAmount: 0 },
    { id: 189, title: 'Saint Vincent and the Grenadines', singleAmount: 0, extraAmount: 0 },
    { id: 190, title: 'Samoa', singleAmount: 0, extraAmount: 0 },
    { id: 191, title: 'San Marino', singleAmount: 0, extraAmount: 0 },
    { id: 192, title: 'Sao Tome and Principe', singleAmount: 0, extraAmount: 0 },
    { id: 193, title: 'Saudi Arabia', singleAmount: 0, extraAmount: 0 },
    { id: 194, title: 'Senegal', singleAmount: 0, extraAmount: 0 },
    { id: 195, title: 'Serbia', singleAmount: 0, extraAmount: 0 },
    { id: 196, title: 'Seychelles', singleAmount: 0, extraAmount: 0 },
    { id: 197, title: 'Sierra Leone', singleAmount: 0, extraAmount: 0 },
    { id: 198, title: 'Singapore', singleAmount: 0, extraAmount: 0 },
    { id: 199, title: 'Sint Maarten (Dutch part)', singleAmount: 0, extraAmount: 0 },
    { id: 200, title: 'Slovakia', singleAmount: 0, extraAmount: 0 },
    { id: 201, title: 'Slovenia', singleAmount: 0, extraAmount: 0 },
    { id: 202, title: 'Solomon Islands', singleAmount: 0, extraAmount: 0 },
    { id: 203, title: 'Somalia', singleAmount: 0, extraAmount: 0 },
    { id: 204, title: 'South Africa', singleAmount: 0, extraAmount: 0 },
    { id: 205, title: 'South Georgia and the South Sandwich Islands', singleAmount: 0, extraAmount: 0 },
    { id: 206, title: 'South Korea', singleAmount: 0, extraAmount: 0 },
    { id: 207, title: 'Spain', singleAmount: 0, extraAmount: 0 },
    { id: 208, title: 'Spratly Islands', singleAmount: 0, extraAmount: 0 },
    { id: 209, title: 'Sri Lanka', singleAmount: 0, extraAmount: 0 },
    { id: 210, title: 'Sudan', singleAmount: 0, extraAmount: 0 },
    { id: 211, title: 'Suriname', singleAmount: 0, extraAmount: 0 },
    { id: 212, title: 'Svalbard and Jan Mayen', singleAmount: 0, extraAmount: 0 },
    { id: 213, title: 'Swaziland', singleAmount: 0, extraAmount: 0 },
    { id: 214, title: 'Sweden', singleAmount: 0, extraAmount: 0 },
    { id: 215, title: 'Switzerland', singleAmount: 0, extraAmount: 0 },
    { id: 216, title: 'Taiwan', singleAmount: 0, extraAmount: 0 },
    { id: 217, title: 'Tajikistan', singleAmount: 0, extraAmount: 0 },
    { id: 218, title: 'Tanzania, United Republic of', singleAmount: 0, extraAmount: 0 },
    { id: 219, title: 'Thailand', singleAmount: 0, extraAmount: 0 },
    { id: 220, title: 'The Bahamas', singleAmount: 0, extraAmount: 0 },
    { id: 221, title: 'Togo', singleAmount: 0, extraAmount: 0 },
    { id: 222, title: 'Tokelau', singleAmount: 0, extraAmount: 0 },
    { id: 223, title: 'Tonga', singleAmount: 0, extraAmount: 0 },
    { id: 224, title: 'Trinidad and Tobago', singleAmount: 0, extraAmount: 0 },
    { id: 225, title: 'Tunisia', singleAmount: 0, extraAmount: 0 },
    { id: 226, title: 'Turkey', singleAmount: 0, extraAmount: 0 },
    { id: 227, title: 'Turkmenistan', singleAmount: 0, extraAmount: 0 },
    { id: 228, title: 'Turks and Caicos Islands', singleAmount: 0, extraAmount: 0 },
    { id: 229, title: 'Tuvalu', singleAmount: 0, extraAmount: 0 },
    { id: 230, title: 'Uganda', singleAmount: 0, extraAmount: 0 },
    { id: 231, title: 'Ukraine', singleAmount: 0, extraAmount: 0 },
    { id: 232, title: 'United Arab Emirates', singleAmount: 0, extraAmount: 0 },
    { id: 233, title: 'United Kingdom', singleAmount: 0, extraAmount: 0 },
    { id: 234, title: 'United Nations Neutral Zone', singleAmount: 0, extraAmount: 0 },
    { id: 235, title: 'United States', singleAmount: 0, extraAmount: 0 },
    { id: 236, title: 'United States Minor Outlying Islands', singleAmount: 0, extraAmount: 0 },
    { id: 237, title: 'Uruguay', singleAmount: 0, extraAmount: 0 },
    { id: 238, title: 'Uzbekistan', singleAmount: 0, extraAmount: 0 },
    { id: 239, title: 'Vanuatu', singleAmount: 0, extraAmount: 0 },
    { id: 240, title: 'Venezuela', singleAmount: 0, extraAmount: 0 },
    { id: 241, title: 'Vietnam', singleAmount: 0, extraAmount: 0 },
    { id: 242, title: 'Virgin Islands, U.S.', singleAmount: 0, extraAmount: 0 },
    { id: 243, title: 'Wallis and Futuna', singleAmount: 0, extraAmount: 0 },
    { id: 244, title: 'Western Sahara', singleAmount: 0, extraAmount: 0 },
    { id: 245, title: 'Yemen', singleAmount: 0, extraAmount: 0 },
    { id: 246, title: 'Zambia', singleAmount: 0, extraAmount: 0 },
    { id: 247, title: 'Zimbabwe', singleAmount: 0, extraAmount: 0 }
];
